from __future__ import annotations

import shutil
from pathlib import Path
from typing import Any

_COMMON_WINDOWS_INSTALL_PATHS = (
    Path(r"C:\Program Files\Tesseract-OCR\tesseract.exe"),
    Path(r"C:\Program Files (x86)\Tesseract-OCR\tesseract.exe"),
)


def locate_tesseract_binary() -> str | None:
    """Find the Tesseract binary even when a fresh install has not propagated to the
    current process's PATH yet - a live Windows PATH change does not reach an
    already-running process, the same class of gotcha as Ollama's registry keypair
    needing to be generated by hand. Checks PATH first, then the standard Windows
    install locations winget/the official installer use.
    """

    on_path = shutil.which("tesseract")
    if on_path:
        return on_path
    for candidate in _COMMON_WINDOWS_INSTALL_PATHS:
        if candidate.is_file():
            return str(candidate)
    return None


def configure_pytesseract() -> bool:
    """Point pytesseract at a located binary. Idempotent and cheap to call before
    every OCR attempt. Returns whether a binary was found."""

    binary = locate_tesseract_binary()
    if binary is None:
        return False
    try:
        import pytesseract

        pytesseract.pytesseract.tesseract_cmd = binary
    except ImportError:
        return False
    return True


class OcrUnavailable(RuntimeError):
    pass


def ocr_image_with_confidence(image: Any) -> tuple[str, float, int]:
    """Run Tesseract with real per-word confidence, returning (text, mean_confidence,
    word_count). Confidence is the mean of Tesseract's own per-word scores (0-100,
    rescaled to 0-1) over recognized words only - replaces the previous hardcoded
    0.6/0.65 placeholders with a number that actually reflects what was read.
    """

    if not configure_pytesseract():
        raise OcrUnavailable("tesseract binary not found on PATH or in standard install locations")

    import pytesseract
    from pytesseract import Output

    data = pytesseract.image_to_data(image, output_type=Output.DICT)
    words: list[str] = []
    confidences: list[float] = []
    for text, conf in zip(data["text"], data["conf"], strict=True):
        stripped = text.strip()
        if not stripped:
            continue
        try:
            conf_value = float(conf)
        except (TypeError, ValueError):
            continue
        if conf_value < 0:  # Tesseract uses -1 for non-text regions
            continue
        words.append(stripped)
        confidences.append(conf_value)

    full_text = " ".join(words)
    mean_confidence = (sum(confidences) / len(confidences) / 100.0) if confidences else 0.0
    return full_text, round(mean_confidence, 4), len(words)
