import { api } from './api'

/**
 * Evaluation Studio exports (design §15.5 "export CSV, JSON, and Markdown reports").
 *
 * The report bodies are generated by the backend — `GET /experiments/{id}/report`
 * already renders all three formats from the persisted `ExperimentRecord`, so the
 * frontend must never re-derive them: two independent renderings of the same metrics
 * would be two chances to disagree about what was measured. This module only turns
 * the fetched text into a download.
 */

export type ExportFormat = 'json' | 'markdown' | 'csv'

const EXTENSIONS: Record<ExportFormat, string> = { json: 'json', markdown: 'md', csv: 'csv' }
const MEDIA_TYPES: Record<ExportFormat, string> = {
  json: 'application/json',
  markdown: 'text/markdown',
  csv: 'text/csv',
}

export const reportFilename = (experimentId: string, format: ExportFormat): string =>
  `${experimentId}.${EXTENSIONS[format]}`

/** Trigger a browser download of `content`. Exported for testing the naming rules. */
export function downloadText(filename: string, content: string, mediaType: string): void {
  const url = URL.createObjectURL(new Blob([content], { type: mediaType }))
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = filename
  document.body.append(anchor)
  anchor.click()
  anchor.remove()
  URL.revokeObjectURL(url)
}

export async function exportExperimentReport(experimentId: string, format: ExportFormat): Promise<string> {
  const body = await api.experimentReport(experimentId, format)
  downloadText(reportFilename(experimentId, format), body, MEDIA_TYPES[format])
  return body
}

export type QuestionFailure = {
  kind: 'miss' | 'low-rank' | 'wrong-abstention' | 'missed-abstention' | 'ok'
  explanation: string
}

/**
 * Why a single benchmark question scored the way it did (design §15.5 "drill into
 * individual questions and failure causes").
 *
 * The categories are read off the measured numbers, never guessed: an answerable
 * question whose relevant chunks never appeared is a retrieval miss; one that appeared
 * outside the top rank is a ranking problem; abstention errors are their own class
 * because §14.7 gates them separately.
 */
export function classifyQuestion(result: {
  success_at_k: number
  recall_at_k: number
  reciprocal_rank: number
  relevant_chunk_ids: string[]
  predicted_abstention: boolean
  abstention_correct: boolean | null
}): QuestionFailure {
  const answerable = result.relevant_chunk_ids.length > 0
  if (!answerable) {
    if (result.abstention_correct === false) {
      return {
        kind: 'missed-abstention',
        explanation: 'Unanswerable question — the system returned evidence instead of abstaining.',
      }
    }
    return { kind: 'ok', explanation: 'Unanswerable question — correctly abstained.' }
  }
  if (result.predicted_abstention) {
    return {
      kind: 'wrong-abstention',
      explanation: 'Answerable question — the evidence gate abstained even though relevant chunks exist.',
    }
  }
  if (result.success_at_k === 0) {
    return {
      kind: 'miss',
      explanation: `Retrieval miss — none of the ${result.relevant_chunk_ids.length} judged chunk(s) reached the top-k.`,
    }
  }
  if (result.reciprocal_rank < 1) {
    return {
      kind: 'low-rank',
      explanation: `Ranking problem — the first relevant chunk landed at rank ${Math.round(1 / result.reciprocal_rank)}.`,
    }
  }
  if (result.recall_at_k < 1) {
    return {
      kind: 'low-rank',
      explanation: `Partial recall — ${Math.round(result.recall_at_k * 100)}% of the judged chunks were retrieved.`,
    }
  }
  return { kind: 'ok', explanation: 'All judged chunks retrieved, top-ranked.' }
}

/** Metric deltas between two experiment manifests (design §15.5 "compare manifests"). */
export function compareMetrics(
  left: Array<{ name: string; value: number }>,
  right: Array<{ name: string; value: number }>,
): Array<{ name: string; left: number | null; right: number | null; delta: number | null }> {
  const names = [...new Set([...left.map((item) => item.name), ...right.map((item) => item.name)])].sort()
  return names.map((name) => {
    const leftValue = left.find((item) => item.name === name)?.value ?? null
    const rightValue = right.find((item) => item.name === name)?.value ?? null
    return {
      name,
      left: leftValue,
      right: rightValue,
      delta: leftValue !== null && rightValue !== null ? rightValue - leftValue : null,
    }
  })
}
