import { describe, expect, it } from 'vitest'
import { generationBadge, generationProvenance, generationSummary } from './generation'

const trace = (over: Record<string, unknown> = {}) =>
  ({ model: 'llama3.1:8b', generation_mode: 'model', generation_fallback_reason: null, ...over }) as never

describe('generation provenance', () => {
  it('never presents an extractive fallback as a resolved model answer', () => {
    const badge = generationBadge({
      insufficient_evidence: false,
      trace: trace({ generation_mode: 'extractive-fallback', generation_fallback_reason: 'ConnectError' }),
    })
    expect(badge).toEqual({ tone: 'warn', label: 'not model-generated' })
  })

  it('marks a real completion as a model answer', () => {
    expect(generationBadge({ insufficient_evidence: false, trace: trace() })).toEqual({
      tone: 'good',
      label: 'model answer · labels resolved',
    })
  })

  it('abstention outranks generation mode', () => {
    expect(generationBadge({ insufficient_evidence: true, trace: trace() }).label).toBe('abstain')
  })

  it('names the model only when the model actually ran', () => {
    expect(generationSummary(trace())).toBe('generated by llama3.1:8b')
    expect(generationSummary(trace({ generation_mode: 'extractive-fallback' }))).toBe(
      'extractive fallback — model unavailable',
    )
  })

  it('reports why generation degraded', () => {
    expect(
      generationProvenance(trace({ generation_mode: 'extractive-fallback', generation_fallback_reason: 'ConnectError' })),
    ).toBe('extractive fallback (ConnectError)')
  })
})

describe('abstention', () => {
  it('does not claim the model produced an abstention', () => {
    const abstained = { model: 'llama3.1:8b', generation_mode: 'abstained', generation_fallback_reason: null } as never
    expect(generationSummary(abstained)).toBe('abstained — no model call')
    expect(generationProvenance(abstained)).toBe('no generation — retrieval found no supporting evidence')
  })
})
