import type { QueryResponse } from './api'

export type GenerationBadge = { tone: 'good' | 'warn'; label: string }

/**
 * The fallback answer carries [S1] labels, so "labels resolved" is true of it and
 * still misleading. Answer provenance is therefore decided before citation state.
 */
export function generationBadge(
  result: Pick<QueryResponse, 'insufficient_evidence' | 'trace'>,
  resolvedLabel = 'model answer · labels resolved',
): GenerationBadge {
  if (result.insufficient_evidence) return { tone: 'warn', label: 'abstain' }
  if (result.trace.generation_mode === 'extractive-fallback') {
    return { tone: 'warn', label: 'not model-generated' }
  }
  return { tone: 'good', label: resolvedLabel }
}

export function generationSummary(trace: QueryResponse['trace']): string {
  if (trace.generation_mode === 'abstained') return 'abstained — no model call'
  return trace.generation_mode === 'extractive-fallback'
    ? 'extractive fallback — model unavailable'
    : `generated by ${trace.model}`
}

export function generationProvenance(trace: QueryResponse['trace']): string {
  if (trace.generation_mode === 'abstained') {
    return 'no generation — retrieval found no supporting evidence'
  }
  return trace.generation_mode === 'extractive-fallback'
    ? `extractive fallback (${trace.generation_fallback_reason ?? 'model unavailable'})`
    : trace.model
}
